name: CuriousCustoms
favicon: null
layout_spectrum: 0.9718431774526834
typography_spectrum: 0.3491656379774213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcaa9c'
    - '#8bb7de'
    - '#6d625c'
    - '#1e1c1f'
    - '#fcdfbb'
  brandStrength: 0.31836203509010375
  lightness: 0.47821633727289736
  saturation: 0.42830929858610034
  rhythmicContrast: 0.4400528387632221
purpose: []
